version: "3"

services:
  rosbridge:
    build: .
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - ROS_MASTER_URI=http://172.17.1.1:11311 #IP OF DEVICE RUNNING ROSCORE
      - ROS_IP=172.17.1.2 #LOCAL HOST IP
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && roslaunch --wait rosbridge_server rosbridge_websocket.launch'

  main:
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://172.17.1.1:11311
      - ROS_IP=172.17.1.2
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros:/catkin_ws/src/ros
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    depends_on:
      - rosbridge
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    command: bash
