version: "3"

services:
  roscore:
    image: franka_ros:latest
    build: .docker
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: roscore

  cartesian_impedance_control:
    image: franka_ros:latest
    build: .docker
    environment:
      - DISPLAY=${DISPLAY}
      - GAZEBO_MODEL_PATH=/catkin_ws/src/franka_ros/franka_description/robots
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.docker/cartesian_impedance_example_controller_no_marker.launch:/catkin_ws/src/franka_ros/franka_example_controllers/launch/cartesian_impedance_example_controller_no_marker.launch
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    depends_on:
      - roscore
    command: /bin/bash -c '. /catkin_ws/devel/setup.bash && roslaunch --wait franka_example_controllers cartesian_impedance_example_controller_no_marker.launch robot:=fr3 load_gripper:=True'

  main:
    image: franka_ros:latest
    build: .docker
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./realm:/catkin_ws/src/realm
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - roscore
    command: bash
